import type { DadosPlaneta, IdPlaneta } from '../tipos';

export const PLANETAS: readonly DadosPlaneta[] = [
  {
    id: 'mercurio',
    nome: 'Mercúrio',
    tipo: 'Planeta rochoso',
    descricao:
      'O menor planeta do Sistema Solar percorre a órbita mais próxima do Sol. Sua superfície marcada por crateras registra bilhões de anos de impactos.',
    diametroKm: 4_879,
    distanciaMediaSolKm: 58_000_000,
    gravidadeMs2: 3.7,
    temperaturaMediaC: 167,
    duracaoDia: '59 dias terrestres',
    duracaoAno: '88 dias terrestres',
    numeroDeLuas: 0,
    curiosidade:
      'Apesar de estar mais perto do Sol, Mercúrio não é o planeta mais quente: sua atmosfera quase inexistente não consegue reter calor.',
    fonte: 'https://science.nasa.gov/mercury/facts/',
    texturaAlta: 'mercurio-2k.jpg',
    texturaBaixa: 'mercurio-1k.jpg',
    raioVisual: 0.48,
    distanciaOrbitalVisual: 9,
    velocidadeOrbital: 0.39,
    velocidadeRotacao: 0.08,
    inclinacaoAxialGraus: 0.03,
    faseInicial: 0.3,
    corDestaque: '#b8aa98',
    corFallback: 0x8e8378,
  },
  {
    id: 'venus',
    nome: 'Vênus',
    tipo: 'Planeta rochoso',
    descricao:
      'Coberto por nuvens espessas de ácido sulfúrico, Vênus possui uma atmosfera que aprisiona calor e torna sua superfície a mais quente entre os planetas.',
    diametroKm: 12_104,
    distanciaMediaSolKm: 108_200_000,
    gravidadeMs2: 8.87,
    temperaturaMediaC: 464,
    duracaoDia: '243 dias terrestres',
    duracaoAno: '225 dias terrestres',
    numeroDeLuas: 0,
    curiosidade:
      'Vênus gira lentamente no sentido oposto ao da maioria dos planetas; ali, o Sol aparentaria nascer no oeste.',
    fonte: 'https://science.nasa.gov/venus/venus-facts/',
    texturaAlta: 'venus-2k.jpg',
    texturaBaixa: 'venus-1k.jpg',
    raioVisual: 0.95,
    distanciaOrbitalVisual: 13,
    velocidadeOrbital: 0.32,
    velocidadeRotacao: -0.025,
    inclinacaoAxialGraus: 177.4,
    faseInicial: 1.55,
    corDestaque: '#f0bd73',
    corFallback: 0xc9914f,
    atmosfera: { cor: 0xf5b85b, opacidade: 0.12, escala: 1.035 },
  },
  {
    id: 'terra',
    nome: 'Terra',
    tipo: 'Planeta rochoso',
    descricao:
      'Nosso planeta combina oceanos de água líquida, atmosfera protetora e uma faixa de temperaturas que sustenta uma extraordinária diversidade de vida.',
    diametroKm: 12_756,
    distanciaMediaSolKm: 149_600_000,
    gravidadeMs2: 9.81,
    temperaturaMediaC: 15,
    duracaoDia: '23 h 56 min',
    duracaoAno: '365,25 dias',
    numeroDeLuas: 1,
    curiosidade:
      'A Lua ajuda a estabilizar a inclinação do eixo terrestre, reduzindo variações climáticas extremas ao longo de milhares de anos.',
    fonte: 'https://science.nasa.gov/earth/facts/',
    texturaAlta: 'terra-2k.jpg',
    texturaBaixa: 'terra-1k.jpg',
    raioVisual: 1,
    distanciaOrbitalVisual: 17,
    velocidadeOrbital: 0.275,
    velocidadeRotacao: 0.48,
    inclinacaoAxialGraus: 23.4,
    faseInicial: 2.8,
    corDestaque: '#59a9ff',
    corFallback: 0x2f71aa,
    atmosfera: { cor: 0x4da6ff, opacidade: 0.18, escala: 1.045 },
    nuvens: {
      texturaAlta: 'terra-nuvens-2k.jpg',
      texturaBaixa: 'terra-nuvens-1k.jpg',
      velocidadeRotacao: 0.53,
    },
    lua: {
      texturaAlta: 'lua-2k.jpg',
      texturaBaixa: 'lua-1k.jpg',
      raioVisual: 0.27,
      distanciaOrbital: 2.1,
      velocidadeOrbital: 0.8,
    },
  },
  {
    id: 'marte',
    nome: 'Marte',
    tipo: 'Planeta rochoso',
    descricao:
      'Óxidos de ferro dão a Marte sua cor avermelhada. O planeta preserva vulcões gigantes, vales profundos e sinais de que água líquida já percorreu sua superfície.',
    diametroKm: 6_792,
    distanciaMediaSolKm: 227_900_000,
    gravidadeMs2: 3.71,
    temperaturaMediaC: -63,
    duracaoDia: '24 h 37 min',
    duracaoAno: '687 dias terrestres',
    numeroDeLuas: 2,
    curiosidade:
      'O Olympus Mons se eleva cerca de 22 quilômetros e é o maior vulcão conhecido do Sistema Solar.',
    fonte: 'https://science.nasa.gov/mars/facts/',
    texturaAlta: 'marte-2k.jpg',
    texturaBaixa: 'marte-1k.jpg',
    raioVisual: 0.55,
    distanciaOrbitalVisual: 22,
    velocidadeOrbital: 0.225,
    velocidadeRotacao: 0.46,
    inclinacaoAxialGraus: 25.2,
    faseInicial: 4.1,
    corDestaque: '#d77950',
    corFallback: 0xa54b32,
  },
  {
    id: 'jupiter',
    nome: 'Júpiter',
    tipo: 'Gigante gasoso',
    descricao:
      'O maior planeta do Sistema Solar é uma esfera de hidrogênio e hélio marcada por faixas de nuvens, tempestades persistentes e um poderoso campo magnético.',
    diametroKm: 142_984,
    distanciaMediaSolKm: 778_500_000,
    gravidadeMs2: 24.79,
    temperaturaMediaC: -110,
    duracaoDia: '9 h 56 min',
    duracaoAno: '11,86 anos terrestres',
    numeroDeLuas: 95,
    curiosidade:
      'A Grande Mancha Vermelha é uma tempestade maior que a Terra observada há séculos na atmosfera joviana.',
    fonte: 'https://science.nasa.gov/jupiter/jupiter-facts/',
    texturaAlta: 'jupiter-2k.jpg',
    texturaBaixa: 'jupiter-1k.jpg',
    raioVisual: 3.4,
    distanciaOrbitalVisual: 31,
    velocidadeOrbital: 0.15,
    velocidadeRotacao: 0.72,
    inclinacaoAxialGraus: 3.1,
    faseInicial: 5.25,
    corDestaque: '#d5a477',
    corFallback: 0xb98f6c,
  },
  {
    id: 'saturno',
    nome: 'Saturno',
    tipo: 'Gigante gasoso',
    descricao:
      'Saturno é envolvido por milhares de anéis formados principalmente por partículas de gelo e rocha, compondo o sistema de anéis mais visível do Sistema Solar.',
    diametroKm: 120_536,
    distanciaMediaSolKm: 1_434_000_000,
    gravidadeMs2: 10.44,
    temperaturaMediaC: -140,
    duracaoDia: '10 h 42 min',
    duracaoAno: '29,5 anos terrestres',
    numeroDeLuas: 274,
    curiosidade:
      'A densidade média de Saturno é menor que a da água, embora não exista um oceano grande o bastante para testar essa comparação.',
    fonte: 'https://science.nasa.gov/saturn/facts/',
    texturaAlta: 'saturno-2k.jpg',
    texturaBaixa: 'saturno-1k.jpg',
    raioVisual: 3,
    distanciaOrbitalVisual: 41,
    velocidadeOrbital: 0.11,
    velocidadeRotacao: 0.66,
    inclinacaoAxialGraus: 26.7,
    faseInicial: 0.95,
    corDestaque: '#e4c48c',
    corFallback: 0xc7a872,
    aneis: {
      raioInterno: 1.22,
      raioExterno: 2.05,
      textura: 'aneis-saturno-2k.png',
      opacidade: 0.86,
    },
  },
  {
    id: 'urano',
    nome: 'Urano',
    tipo: 'Gigante de gelo',
    descricao:
      'Metano na atmosfera dá a Urano seu tom azul-esverdeado. O planeta gira praticamente de lado, como se rolasse ao longo de sua órbita.',
    diametroKm: 51_118,
    distanciaMediaSolKm: 2_871_000_000,
    gravidadeMs2: 8.69,
    temperaturaMediaC: -195,
    duracaoDia: '17 h 14 min',
    duracaoAno: '84 anos terrestres',
    numeroDeLuas: 28,
    curiosidade:
      'Sua inclinação de aproximadamente 98 graus produz estações extremas que duram décadas terrestres.',
    fonte: 'https://science.nasa.gov/uranus/facts/',
    texturaAlta: 'urano-2k.jpg',
    texturaBaixa: 'urano-1k.jpg',
    raioVisual: 1.75,
    distanciaOrbitalVisual: 51,
    velocidadeOrbital: 0.082,
    velocidadeRotacao: -0.55,
    inclinacaoAxialGraus: 97.8,
    faseInicial: 2.15,
    corDestaque: '#8fdbe2',
    corFallback: 0x78c7ce,
    atmosfera: { cor: 0x9ce8e8, opacidade: 0.08, escala: 1.025 },
  },
  {
    id: 'netuno',
    nome: 'Netuno',
    tipo: 'Gigante de gelo',
    descricao:
      'Distante e turbulento, Netuno possui uma atmosfera azul profunda atravessada pelos ventos mais rápidos já medidos em um planeta do Sistema Solar.',
    diametroKm: 49_528,
    distanciaMediaSolKm: 4_495_000_000,
    gravidadeMs2: 11.15,
    temperaturaMediaC: -200,
    duracaoDia: '16 h 6 min',
    duracaoAno: '164,8 anos terrestres',
    numeroDeLuas: 16,
    curiosidade:
      'Netuno foi localizado em 1846 a partir de previsões matemáticas antes de ser observado diretamente por telescópio.',
    fonte: 'https://science.nasa.gov/neptune/neptune-facts/',
    texturaAlta: 'netuno-2k.jpg',
    texturaBaixa: 'netuno-1k.jpg',
    raioVisual: 1.7,
    distanciaOrbitalVisual: 61,
    velocidadeOrbital: 0.065,
    velocidadeRotacao: 0.58,
    inclinacaoAxialGraus: 28.3,
    faseInicial: 3.55,
    corDestaque: '#4b7dff',
    corFallback: 0x315dcc,
    atmosfera: { cor: 0x3f72ff, opacidade: 0.11, escala: 1.03 },
  },
] as const;

export const PLANETAS_POR_ID = new Map<IdPlaneta, DadosPlaneta>(
  PLANETAS.map((planeta) => [planeta.id, planeta]),
);

export function obterPlaneta(id: IdPlaneta): DadosPlaneta {
  const planeta = PLANETAS_POR_ID.get(id);

  if (!planeta) {
    throw new Error(`Planeta não encontrado: ${id}`);
  }

  return planeta;
}
